#ifndef HOMUNCULUS_HOMUNCULUSCONFIG_H
#define HOMUNCULUS_HOMUNCULUSCONFIG_H

#define SPI_BUFFER_SIZE 10
#define HOMUNCULUS Calypso

//#define SPI_BUFFER_SIZE 10
//#define HOMUNCULUS Gemini

//#define SPI_BUFFER_SIZE 10
//#define HOMUNCULUS Geminus

#endif //HOMUNCULUS_HOMUNCULUSCONFIG_H
